mode: live
exchange:
  name: kraken

trading:
  base_ccy: USD
  symbols:
    - BTC/USD
    - ETH/USD
    - SOL/USD
    - LINK/USD
    - AVAX/USD
    - APT/USD
    - ARB/USD

  lookback_days: 90
  min_weight: 0.05
  max_weight: 0.60

  # Optional knobs (remove any/all; trade.py has defaults)
  turnover_cap: 0.10
  regime_tuners:
    bull:
      cash_buffer: 0.15
      max_positions: 4
      lam: 0.40
    chop:
      cash_buffer: 0.35
      max_positions: 2
      lam: 0.60
    bear:
      cash_buffer: 0.55
      max_positions: 1
      lam: 0.80

logging:
  level: INFO
state_file: state/state.json


