mode: paper
exchange:
  name: kraken
trading:
  base_ccy: USDT
  cash_buffer_pct: 0.15
  max_positions: 3
  lookback_days: 90
  rebalance_days: 7
  min_weight: 0.05
  max_weight: 0.6
  risk_aversion: 0.5
  symbols:
    - BTC/USDT
    - ETH/USDT
    - SOL/USDT
    - LINK/USDT
    - AVAX/USDT
    - APT/USDT
    - ARB/USDT
logging:
  level: INFO
state_file: state/state.json
