name: summary

on:
  schedule:
    - cron: "15 0 * * *"   # every day at 00:15 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install (only what's needed)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send PnL summary
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -m bot.summary
