name: trade

on:
  schedule:
    - cron: "0 */8 * * *"  # every 8 hours
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Only Actions installs the quantum deps:
          if [ -f requirements-quantum.txt ]; then pip install -r requirements-quantum.txt; fi
      - name: Trade
        env:
          EXCHANGE_KEY: ${{ secrets.EXCHANGE_KEY }}
          EXCHANGE_SECRET: ${{ secrets.EXCHANGE_SECRET }}
          EXCHANGE_PASSWORD: ${{ secrets.EXCHANGE_PASSWORD }}
          DWAVE_API_TOKEN: ${{ secrets.DWAVE_API_TOKEN }}
        run: |
          python -m bot.trade

